### ISSUE TITLE
Working On UI

### ISSUE THREAD

**Issue by Kritika30032002** [mohitahlawat2001/shiny-octo-planner-app#1]
card components are not placed correctly. Its UI can be improved.
 Assign this to me

**Comment by mohitahlawat2001** [comment]
create another branch for this

**Comment by Kritika30032002** [comment]
Update the readme so that I can know the steps for local setup @mohitahlawat2001

**Comment by mohitahlawat2001** [comment]
I updated readme, you can see now.

**Comment by Kritika30032002** [comment]
okay
