### ISSUE TITLE
Unable to fetch quotes

### ISSUE THREAD

**Issue by Villain45** [mohitahlawat2001/shiny-octo-planner-app#10]
The functionality of fetching quotes is not working, would like to work on this issue

**Comment by mohitahlawat2001** [comment]
i assigned this to you,

> make sure you star ⭐ repo if like and follow on github

**Comment by nidhi752** [comment]
Hi, I see that this issue is still not resolved. Please assign this to me under hackoctoberfest.
@mohitahlawat2001
