### ISSUE TITLE
Feature: Adding a  Weather widget 

### ISSUE THREAD

**Issue by haseebzaki-07** [mohitahlawat2001/shiny-octo-planner-app#15]
I want to add a weather widget that shows real-time weather situations.

**Comment by mohitahlawat2001** [comment]
Also have one

**Comment by mohitahlawat2001** [comment]
Already have one

**Comment by haseebzaki-07** [comment]
so can I add a realtime news fetching widget

**Comment by haseebzaki-07** [comment]
or any new thing that you want

**Comment by mohitahlawat2001** [comment]
Realtime news already exists

**Comment by mohitahlawat2001** [comment]
can make recording , camera , video widget

**Comment by haseebzaki-07** [comment]
Sure I will, which one!

**Comment by mohitahlawat2001** [comment]
make issue with any one of them
