### ISSUE TITLE
[FEATURE] : Video recorder widget

### ISSUE THREAD

**Issue by haseebzaki-07** [mohitahlawat2001/shiny-octo-planner-app#16]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I want to create a video recorder widget for the application.

### Proposed Solution

A video recording widget can have a wide range of features depending on the use case and complexity. Below are some common  features that can be implemented in a video recording widget start/stop recording, preview videos etc.

### Do you want to work on this issue?

Yes

**Comment by mohitahlawat2001** [comment]
@haseebzaki-07 
 i assign you this issue , post video or photo of site , when you make Pr

> make sure you star ⭐ repo if you like and follow on github

**Comment by haseebzaki-07** [comment]
Sure
