### ISSUE TITLE
[README.MD update] Incorrect info on the readme.md page

### ISSUE THREAD

**Issue by akku-07** [mohitahlawat2001/shiny-octo-planner-app#17]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

the readme.md page has the installation procedure of the calculator app, i want to correct that

### Steps to Reproduce

Include any relevant details like:

- Readme.md
- trying to install the code on my PC
- incorrect installation, downloaded the calculator app instead

### Screenshots

![image](https://github.com/user-attachments/assets/1703d7a5-f378-4916-bbc7-4cd5132e1cc4)

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

fix the readme.md page!

**Comment by mohitahlawat2001** [comment]
@akku-07  i assign you this issue , 

> make sure you star ⭐ repo if you like and follow on github

**Comment by akku-07** [comment]
thank you sir!

**Comment by akku-07** [comment]
sir could you also add it under hacktoberfest please?
