### ISSUE TITLE
[BUG] The Components or the Cards are floating outside of the screen

### ISSUE THREAD

**Issue by TheSoumenMondal** [mohitahlawat2001/shiny-octo-planner-app#19]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

To ensure a more professional and seamless user experience while dragging cards on your website, you can implement boundaries to prevent the cards from being dragged outside the visible screen area.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

**Use the framer motion to fix this. Simply set the dragConstraints...**

**Comment by TheSoumenMondal** [comment]
Please assign me this issue

**Comment by mohitahlawat2001** [comment]
not able to understand issue , can you show photo or video

**Comment by TheSoumenMondal** [comment]
![image](https://github.com/user-attachments/assets/b575e347-2d75-4e0c-a93f-ae25e4e42208)
When i made the Tic-Tac-Toe Card Floating its going outside my screen area . If i drag this too much it will be lost . So its better to set a boundary for the cards when they are in floating state

**Comment by mohitahlawat2001** [comment]
@TheSoumenMondal  i assign you this issue , post video or photo of site , when you make Pr

> make sure you star ⭐ repo  and follow on github

**Comment by TheSoumenMondal** [comment]
Can you please add it under hacktoberfest ?
