### ISSUE TITLE
LICENSE for the repo

### ISSUE THREAD

**Issue by akku-07** [mohitahlawat2001/shiny-octo-planner-app#21]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

the repository does not have a license

### Proposed Solution

adding a license

### Screenshots

adding a license

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

adding a license

**Comment by mohitahlawat2001** [comment]
@akku-07  i assign you this issue 

> make sure you star ⭐ repo if you like and follow on github

**Comment by akku-07** [comment]
thankn you sir!could you also add it under hacktoberfest please?

**Comment by akku-07** [comment]
could you also add it under hacktoberfest please?
