### ISSUE TITLE
[FEATURE] : Docekrize the Application

### ISSUE THREAD

**Issue by haseebzaki-07** [mohitahlawat2001/shiny-octo-planner-app#29]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

A Dockerfile simplifies deployment by packaging a full stack app, including all dependencies, into a consistent environment, ensuring smooth operation across different systems. It also streamlines testing, scaling, and collaboration, enabling easy setup and maintenance through containerization.

### Proposed Solution

Adding a Dockerfile to the root of the project

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will add a Docekrfile to the root of the application that will build the images by reading add the files of the application  and then the image can be run using some docker command.

**Comment by Shivam-Batham** [comment]
@haseebzaki-07 I want to take this issue, assign it to me
