### ISSUE TITLE
Cursor doesn’t changes to pointer on hover.

### ISSUE THREAD

**Issue by Piyush-Goenka** [mohitahlawat2001/shiny-octo-planner-app#32]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

On hover on upper left drop down box cursor doesn’t  changes to pointer. 
On hover over the dropdown menu cursor should change to pointer.

### Steps to Reproduce

To view this just hover over the dropdown menu .

### Screenshots

<img width="1784" alt="Screenshot 2024-10-07 at 11 39 23 PM" src="https://github.com/user-attachments/assets/9658d077-be0f-4053-95b6-e26063ea1b4c">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

To change the cursor to a pointer when hovering over a dropdown menu, add a CSS rule using the :hover pseudo-class. Set the cursor property to pointer for the dropdown items.

**Comment by Piyush-Goenka** [comment]
Hey @mohitahlawat2001 
I want to work on this issue .
Please assign this issue to me.

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Piyush-Goenka** [comment]
I have made the pr please check and let me know if any modifications/changes needed.
https://github.com/mohitahlawat2001/shiny-octo-planner-app/pull/42
Thanks!

**Comment by Piyush-Goenka** [comment]
I am unable to solve this
Unassign me this issue.
