### ISSUE TITLE
[Add Widget is not visible.]

### ISSUE THREAD

**Issue by Piyush-Goenka** [mohitahlawat2001/shiny-octo-planner-app#33]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Add widget option is not visible .
As it is hidden under the video recorder.
The add widget option should be placed at the topmost right corner.

### Steps to Reproduce

Set video recorder to floating then we can find add widget option below it.

### Screenshots

It is not vsible in this image.
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/654f0c2f-4e2d-40a1-840a-8d5b91431ddb">
It is visible once video recorder is moved from its place.
<img width="516" alt="Screenshot 2024-10-08 at 12 44 25 AM" src="https://github.com/user-attachments/assets/3f0f3fae-b8c3-459d-a763-6f4dcc80a011">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will change the position of  "add widget"  and fix it to topmost right corner.

**Comment by Piyush-Goenka** [comment]
Hey @mohitahlawat2001 
I want to work on this issue.
Please assign this issue to me.

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Piyush-Goenka** [comment]
I am unable to solve this
Unassign me this issue.
