### ISSUE TITLE
Add a Calculator Widget

### ISSUE THREAD

**Issue by Piyush-Goenka** [mohitahlawat2001/shiny-octo-planner-app#34]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

There are many widgets but there is no calculator widget.
It would enhance the functionality of the planner.

### Proposed Solution

We may add a calculator widget for the users.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I would simply add one more file for the calculator widget.

**Comment by Piyush-Goenka** [comment]
Hey @mohitahlawat2001 ;
I would like to add a calculator widget .
Please assign me this issue.

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Piyush-Goenka** [comment]
I am unable to solve this
Unassign me this issue.
