### ISSUE TITLE
Add  a "TO DO LIST"

### ISSUE THREAD

**Issue by Piyush-Goenka** [mohitahlawat2001/shiny-octo-planner-app#35]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

It would help users to add the tasks that they want to work on.
It would increase their productivity.

### Proposed Solution

I would just add a  to do widget like other widgets.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I would just add a  to do widget like other widgets.

**Comment by Piyush-Goenka** [comment]
Hey @mohitahlawat2001 ;
Please assign me this issue.
I would like to work on this issue.

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Piyush-Goenka** [comment]
I am unable to solve this
Unassign me this issue.
