### ISSUE TITLE
ADD A POMODRO TIMER WIDGET

### ISSUE THREAD

**Issue by ayyush08** [mohitahlawat2001/shiny-octo-planner-app#37]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I would like to built and add a Pomodro widget to the widget collection.
Please assign this to me.

### Proposed Solution

Pomodoro timers are widely used by people who want to increase productivity by breaking tasks into manageable intervals. Integrating this as a widget in the Planner App will greatly enhance its utility, offering users a built-in time management tool alongside their daily planning.

### Do you want to work on this issue?

Yes

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by ayyush08** [comment]
Thankk you, Gonna buillt it as soon as I can

**Comment by ayyush08** [comment]
I just starred and followed you. Can you please put hacktoberfest label please.

**Comment by ayyush08** [comment]
#38 
 The Pomodro timer is done and working. Kindly look into it and merge my PR
![Screenshot 2024-10-08 190924](https://github.com/user-attachments/assets/e7e985e2-691c-47a4-b3fa-537579b236c1)
