### ISSUE TITLE
[BUG] Responsiveness of the website

### ISSUE THREAD

**Issue by ParvamShah1** [mohitahlawat2001/shiny-octo-planner-app#40]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The website is not at all responsive , elements are getting cut on different dimensions.
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/fdf10dde-77cb-412c-9a5b-06cb3755e71c">
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/338642f4-7da4-4b46-b0c0-c858104b1601">
<img width="653" alt="image" src="https://github.com/user-attachments/assets/f6028101-dbfc-4543-8b6e-62ff477935c9">
In the above images on different dimensions website elements are getting cut. It does'nt show responsiveness.

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...
I was on the homepage of the website, testing its responsiveness across different screen sizes and devices. The goal was to ensure that all elements adapt correctly when the viewport changes. However, I encountered the following issues:

The layout does not adjust properly on smaller screens (e.g., mobile devices). Elements either overlap or do not scale correctlly.
interactive components do not reformat as expected when the screen size changes.
Certain sections do not resize or realign, causing a broken layout or horizontal scrolling.

### Do you want to work on this issue?

Yes

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by ParvamShah1** [comment]
I have followed you and also starred the repo please hacktoberfest tag . 
Already started working on the issue.

Thanks!

**Comment by ParvamShah1** [comment]
completed
