### ISSUE TITLE
[FEATURE] Alarm Widget

### ISSUE THREAD

**Issue by Ananya-Bhardwaj** [mohitahlawat2001/shiny-octo-planner-app#46]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

It is not available, a related functionality is pomodoro timer, but alarm functionality is not there. 

### Proposed Solution

Alarm Widget to enable the user to set an alarm for a specified time 

### Do you want to work on this issue?

Yes

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Ananya-Bhardwaj** [comment]
Done, please add the hacktoberfest label
