### ISSUE TITLE
[FEATURE] Adding a Password Generator Widget

### ISSUE THREAD

**Issue by KrishnaShuk** [mohitahlawat2001/shiny-octo-planner-app#49]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

This Feature Request is related to unavailable functionality.

### Proposed Solution

A Password Generator Widget should be added as an extra functionality.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I'll figure out implementing this.

**Comment by KrishnaShuk** [comment]
Pls assign me this issue and add hacktoberfest tag.

**Comment by Aditya-PS-05** [comment]
Can you assign this task to me?
