### ISSUE TITLE
Covert This create react app to vite 

### ISSUE THREAD

**Issue by Ayusht777** [mohitahlawat2001/shiny-octo-planner-app#5]
I tried to run it, but it has various issues regarding creating a react app. The node module version is old. Due to its slow performance, I want to convert this app to Vite to speed up its performance.

**Comment by mohitahlawat2001** [comment]
open this in codespace for faster performance, 
you can make another branch for this.

**Comment by mohitahlawat2001** [comment]
git fetch origin
git checkout 5-covert-this-create-react-app-to-vite

**Comment by Ayusht777** [comment]
i convert it to vite but their is an issue when pushing it to github

**Comment by mohitahlawat2001** [comment]
did you another branch!

**Comment by Ayusht777** [comment]
hey can you tell me what to do next 
![Screenshot (265)](https://github.com/mohitahlawat2001/shiny-octo-planner-app/assets/106388215/8f20c2e5-6e4b-436a-83cd-70d59122231f)
![Screenshot (266)](https://github.com/mohitahlawat2001/shiny-octo-planner-app/assets/106388215/fed7fc4d-bafa-4b7a-8efc-5f725d334a70)
no option is appearing to create a pull request

**Comment by mohitahlawat2001** [comment]
fork again and try!

**Comment by Ayusht777** [comment]
ok i try several times but not working
